name: Run Tests

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: windows 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6 

    - name: Install dependencies
      run: pip install pytest

    - name: Run tests
      run: pytest
